#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Plot DK318 stratified DGLM degree brainmaps.

Inputs are the full stratified result CSVs generated by dglm_stratified_dk318.R.

Plot rules:
  - Main effects: plot uncorrected p < threshold and whole-brain FDR < threshold.
    Values are signed -log10(raw p).
  - Interaction effects: plot uncorrected p < threshold, whole-brain FDR < threshold,
    and network/restricted-ROI FDR < threshold when network result CSVs are available.
    Values are unsigned -log10(raw p).
"""

import argparse
import os
from glob import glob

import matplotlib.pyplot as plt
import mne
import numpy as np
import pandas as pd
from nibabel.freesurfer.io import read_annot, read_geometry
from nilearn import plotting

BASE_DIR = "/data/home/tqi/data1/share/after_freesurfer"
LH_ANNOT = os.path.join(BASE_DIR, "FILE/DK-318", "lh.DK318.annot")
RH_ANNOT = os.path.join(BASE_DIR, "FILE/DK-318", "rh.DK318.annot")
DEFAULT_RESULT_DIR = os.path.join(BASE_DIR, "FILE/test_mean_1.5/MIND_DK318_DGLM_stratified")


def parse_args():
    parser = argparse.ArgumentParser(description="Plot stratified DK318 DGLM degree brainmaps.")
    parser.add_argument("--result-dir", default=DEFAULT_RESULT_DIR, help="Directory with stratified DGLM outputs.")
    parser.add_argument("--threshold", type=float, default=0.05, help="Significance threshold. Default: 0.05.")
    parser.add_argument("--plot-vmin", type=float, default=1.3, help="Lower colorbar bound for unsigned maps.")
    parser.add_argument("--plot-vmax", type=float, default=3.0, help="Upper colorbar bound.")
    return parser.parse_args()


def safe_name(x):
    return "".join(ch if ch.isalnum() or ch in {"_", "-"} else "_" for ch in str(x)).strip("_")


def strip_hemi_prefix(value):
    return str(value).replace("lh_", "").replace("rh_", "")


def load_fsaverage_and_annot():
    subjects_dir = os.path.join(BASE_DIR, "FILE")
    fs_dir = mne.datasets.fetch_fsaverage(subjects_dir=subjects_dir, verbose=True)
    lh_coords, lh_faces = read_geometry(os.path.join(fs_dir, "surf", "lh.inflated"))
    rh_coords, rh_faces = read_geometry(os.path.join(fs_dir, "surf", "rh.inflated"))
    lh_labels, _, lh_names = read_annot(LH_ANNOT)
    rh_labels, _, rh_names = read_annot(RH_ANNOT)
    if lh_coords.shape[0] != len(lh_labels) or rh_coords.shape[0] != len(rh_labels):
        raise RuntimeError("Surface vertex count does not match annotation labels.")
    return (lh_coords, lh_faces), (rh_coords, rh_faces), lh_labels, lh_names, rh_labels, rh_names


def make_vertex_data(labels, names, roi_map):
    name_list = [name.decode("utf-8") for name in names]
    vertex_data = np.full(labels.shape[0], np.nan, dtype=float)
    hit_count = 0
    for label_id, roi_name in enumerate(name_list):
        if roi_name in roi_map:
            vertex_data[labels == label_id] = float(roi_map[roi_name])
            hit_count += 1
    return vertex_data, hit_count


def add_roi_contours(display, mesh, labels, hemi_name, view, axis):
    try:
        display.add_contours(labels, colors="k", linewidths=0.5)
    except AttributeError:
        plotting.plot_surf_contours(
            surf_mesh=mesh,
            roi_map=labels,
            hemi=hemi_name,
            view=view,
            axes=axis,
            levels=np.unique(labels),
            colors=["black"] * len(np.unique(labels)),
            linewidths=0.2,
        )


def discover_degree_result_files(result_dir):
    files = sorted(glob(os.path.join(result_dir, "DGLM_DK318_*_degree_results.csv")))
    out = []
    for path in files:
        base = os.path.basename(path)
        if base.startswith(("Significant_", "Uncorrected_", "Diagnostic_")):
            continue
        out.append(path)
    return out


def raw_p_columns(df):
    cols = []
    for col in df.columns:
        if not col.startswith(("p_mean_", "p_disp_")):
            continue
        if col.endswith("_FDR") or "_within_network" in col:
            continue
        cols.append(col)
    return cols


def ensure_fdr_columns(df):
    df = df.copy()
    for p_col in raw_p_columns(df):
        fdr_col = p_col + "_FDR"
        if fdr_col not in df.columns:
            p = pd.to_numeric(df[p_col], errors="coerce")
            fdr = np.full(len(df), np.nan, dtype=float)
            valid = p.notna().to_numpy()
            if valid.sum() > 0:
                # Benjamini-Hochberg without scipy/statsmodels dependency.
                pv = p.to_numpy(dtype=float)[valid]
                order = np.argsort(pv)
                ranked = pv[order]
                m = len(ranked)
                adj = ranked * m / np.arange(1, m + 1)
                adj = np.minimum.accumulate(adj[::-1])[::-1]
                adj = np.clip(adj, 0, 1)
                tmp = np.empty_like(adj)
                tmp[order] = adj
                fdr[valid] = tmp
            df[fdr_col] = fdr
    return df


def parse_p_col(p_col):
    if p_col.startswith("p_mean_"):
        return "mean", p_col[len("p_mean_"):]
    if p_col.startswith("p_disp_"):
        return "disp", p_col[len("p_disp_"):]
    return "unknown", p_col


def is_interaction_effect(effect):
    return "Interaction" in effect or effect.count("_") >= 1


def sign_for_main_effect(df, domain, effect):
    sign_col = f"sign_{domain}_{effect}"
    est_col = f"estimate_{domain}_{effect}"
    if sign_col in df.columns:
        sign = pd.to_numeric(df[sign_col], errors="coerce").to_numpy(dtype=float)
    elif est_col in df.columns:
        sign = np.sign(pd.to_numeric(df[est_col], errors="coerce").to_numpy(dtype=float))
    else:
        sign = np.ones(len(df), dtype=float)

    subset_type = None
    if "subset_type" in df.columns and len(df) > 0:
        subset_type = str(df["subset_type"].iloc[0])

    if effect == "Diagnosis" and subset_type == "AgeGroup":
        sign = -sign

    sign[~np.isfinite(sign) | (sign == 0)] = 1.0
    return sign


def build_plot_df(df, p_col, threshold_col, threshold, signed, domain, effect):
    if "feature" not in df.columns or p_col not in df.columns or threshold_col not in df.columns:
        return pd.DataFrame()
    p = pd.to_numeric(df[p_col], errors="coerce")
    q = pd.to_numeric(df[threshold_col], errors="coerce")
    plot_df = df.loc[p.notna() & q.notna() & (p > 0) & (q < threshold)].copy()
    if plot_df.empty:
        return plot_df
    p2 = pd.to_numeric(plot_df[p_col], errors="coerce").clip(lower=np.finfo(float).tiny)
    values = -np.log10(p2.to_numpy(dtype=float))
    if signed:
        sign = sign_for_main_effect(plot_df, domain, effect)
        values = values * sign
    plot_df["roi_norm"] = plot_df["feature"].astype(str).map(strip_hemi_prefix)
    plot_df["minus_log10_p"] = -np.log10(p2.to_numpy(dtype=float))
    plot_df["plot_value"] = values
    plot_df["threshold_value"] = q.loc[plot_df.index].to_numpy(dtype=float)
    return plot_df


def direction_note(domain, effect, subset_type=None):
    if effect == "Diagnosis":
        if subset_type == "AgeGroup":
            return "Red: TD > DD | Blue: DD > TD" if domain == "mean" else "Red: TD more variable | Blue: DD more variable"
        return "Red: DD > TD | Blue: TD > DD" if domain == "mean" else "Red: DD more variable | Blue: TD more variable"
    if effect == "AgeGroup":
        return "Red: Adult > Child | Blue: Child > Adult" if domain == "mean" else "Red: Adult more variable | Blue: Child more variable"
    if effect == "Sex":
        return "Red: Male > Female | Blue: Female > Male" if domain == "mean" else "Red: Male more variable | Blue: Female more variable"
    return None


def plot_surface(plot_df, title, out_dir, signed, args, lh_mesh, rh_mesh, lh_labels, lh_names, rh_labels, rh_names):
    os.makedirs(out_dir, exist_ok=True)
    if plot_df.empty:
        pd.DataFrame([{"message": "No significant ROIs for this threshold."}]).to_csv(
            os.path.join(out_dir, "no_significant_regions.csv"), index=False
        )
        return {"n_roi": 0, "out_dir": out_dir}

    export_cols = [c for c in ["feature", "minus_log10_p", "plot_value", "threshold_value"] if c in plot_df.columns]
    extra_cols = [c for c in plot_df.columns if c.startswith(("estimate_", "p_", "sign_"))]
    export_cols = list(dict.fromkeys(export_cols + extra_cols))
    plot_df[export_cols].sort_values("minus_log10_p", ascending=False).to_csv(
        os.path.join(out_dir, "regions_for_plot.csv"), index=False
    )

    lh_df = plot_df.loc[plot_df["feature"].astype(str).str.startswith("lh_")].copy()
    rh_df = plot_df.loc[plot_df["feature"].astype(str).str.startswith("rh_")].copy()
    lh_map = dict(zip(lh_df["roi_norm"], lh_df["plot_value"]))
    rh_map = dict(zip(rh_df["roi_norm"], rh_df["plot_value"]))
    lh_vtx, lh_hit = make_vertex_data(lh_labels, lh_names, lh_map)
    rh_vtx, rh_hit = make_vertex_data(rh_labels, rh_names, rh_map)

    print("  Plot:", title)
    print("    n_roi:", len(plot_df), "| LH hit:", lh_hit, "| RH hit:", rh_hit)

    plots = [
        ("lh", "lateral", lh_mesh, lh_vtx, "left", lh_labels),
        ("lh", "medial", lh_mesh, lh_vtx, "left", lh_labels),
        ("rh", "lateral", rh_mesh, rh_vtx, "right", rh_labels),
        ("rh", "medial", rh_mesh, rh_vtx, "right", rh_labels),
    ]
    for hemi_tag, view, mesh, vertex_data, hemi_name, labels in plots:
        if not np.isfinite(vertex_data).any():
            print(f"    Skip empty surface: {hemi_tag}_{view} (all NaN)", flush=True)
            continue
        fig = plt.figure(figsize=(6, 6))
        axis = fig.add_subplot(111, projection="3d")
        kwargs = dict(
            surf_mesh=mesh,
            stat_map=vertex_data,
            hemi=hemi_name,
            view=view,
            colorbar=True,
            title=f"{title} | {hemi_tag.upper()} {view}",
            axes=axis,
        )
        if signed:
            kwargs.update(dict(symmetric_cbar=True, vmin=-args.plot_vmax, vmax=args.plot_vmax, cmap="RdBu_r"))
        else:
            kwargs.update(dict(symmetric_cbar=False, vmin=args.plot_vmin, vmax=args.plot_vmax, cmap="Reds"))
        display = plotting.plot_surf_stat_map(**kwargs)
        add_roi_contours(display, mesh, labels, hemi_name, view, axis)
        out_file = os.path.join(out_dir, f"{hemi_tag}_{view}.png")
        fig.savefig(out_file, bbox_inches="tight", pad_inches=0.2, dpi=300)
        plt.close(fig)
    return {"n_roi": int(len(plot_df)), "out_dir": out_dir}


def plot_result_file(csv_path, args, surfaces):
    lh_mesh, rh_mesh, lh_labels, lh_names, rh_labels, rh_names = surfaces
    result_stub = os.path.basename(csv_path).replace(".csv", "")
    df = ensure_fdr_columns(pd.read_csv(csv_path))
    manifest = []

    for p_col in raw_p_columns(df):
        domain, effect = parse_p_col(p_col)
        interaction = is_interaction_effect(effect)
        signed = not interaction

        threshold_specs = [
            ("uncorrected", p_col),
            ("wholebrain_FDR", p_col + "_FDR"),
        ]

        for threshold_name, threshold_col in threshold_specs:
            if threshold_col not in df.columns:
                continue
            plot_df = build_plot_df(df, p_col, threshold_col, args.threshold, signed, domain, effect)
            title = f"{result_stub} | {domain} | {effect} | {threshold_name}"
            subset_type = str(df["subset_type"].iloc[0]) if ("subset_type" in df.columns and len(df) > 0) else None
            note = direction_note(domain, effect, subset_type=subset_type) if signed else None
            if note:
                title = f"{title}\n{note}"
            out_dir = os.path.join(args.result_dir, "stratified_brainmaps", result_stub, domain, effect, threshold_name)
            out = plot_surface(plot_df, title, out_dir, signed, args, lh_mesh, rh_mesh, lh_labels, lh_names, rh_labels, rh_names)
            manifest.append({
                "result_file": csv_path,
                "result_stub": result_stub,
                "domain": domain,
                "effect": effect,
                "threshold": threshold_name,
                "threshold_col": threshold_col,
                "p_col": p_col,
                "n_roi": out["n_roi"],
                "out_dir": out["out_dir"],
            })

        if interaction:
            network_root = os.path.join(args.result_dir, "network_restricted_fdr", result_stub)
            if os.path.isdir(network_root):
                for net_csv in sorted(glob(os.path.join(network_root, "*restricted_fdr.csv"))):
                    try:
                        net_df = pd.read_csv(net_csv)
                    except Exception as exc:
                        print(f"  Skip network CSV {net_csv}: {exc}")
                        continue
                    threshold_col = p_col + "_FDR_within_network"
                    if threshold_col not in net_df.columns:
                        continue
                    network_name = str(net_df.get("network_name", pd.Series([os.path.basename(net_csv)])).iloc[0])
                    plot_df = build_plot_df(net_df, p_col, threshold_col, args.threshold, False, domain, effect)
                    net_tag = safe_name(network_name)
                    title = f"{result_stub} | {domain} | {effect} | network FDR | {network_name}"
                    out_dir = os.path.join(args.result_dir, "stratified_brainmaps", result_stub, domain, effect, "network_FDR", net_tag)
                    out = plot_surface(plot_df, title, out_dir, False, args, lh_mesh, rh_mesh, lh_labels, lh_names, rh_labels, rh_names)
                    manifest.append({
                        "result_file": net_csv,
                        "result_stub": result_stub,
                        "domain": domain,
                        "effect": effect,
                        "threshold": "network_FDR",
                        "network_name": network_name,
                        "threshold_col": threshold_col,
                        "p_col": p_col,
                        "n_roi": out["n_roi"],
                        "out_dir": out["out_dir"],
                    })

    return manifest


def main():
    args = parse_args()
    os.chdir(BASE_DIR)
    result_files = discover_degree_result_files(args.result_dir)
    if not result_files:
        print("No stratified degree result CSVs found.")
        return

    surfaces = load_fsaverage_and_annot()
    manifest_rows = []
    for csv_path in result_files:
        print("Processing result:", csv_path)
        try:
            manifest_rows.extend(plot_result_file(csv_path, args, surfaces))
        except Exception as exc:
            print(f"Skip {csv_path}: {exc}")

    out_root = os.path.join(args.result_dir, "stratified_brainmaps")
    os.makedirs(out_root, exist_ok=True)
    if manifest_rows:
        manifest = pd.DataFrame(manifest_rows)
        manifest.to_csv(os.path.join(out_root, "brainmap_manifest.csv"), index=False)
        overview = manifest.groupby(["domain", "effect", "threshold"], dropna=False).agg(
            n_maps=("out_dir", "count"),
            n_roi_total=("n_roi", "sum"),
        ).reset_index()
        overview.to_csv(os.path.join(out_root, "brainmap_overview.csv"), index=False)
    print("Done plotting stratified brainmaps.")


if __name__ == "__main__":
    main()
